services:
- type: web
  name: client-end
  env: docker
  dockerfilePath: ./client-end/Dockerfile
  envVars:
  - key: REACT_APP_BACKEND
    value: http://localhost/api
- type: web
  name: back-end
  env: docker
  dockerfilePath: ./back-end/Dockerfile
  envVars:
  - key: MONGODB_URL
    value: mongodb+srv://satwik:aneCtJ5dCUd5ofge@satwikbhasin-assignment.dqz7zzb.mongodb.net/?retryWrites=true&w=majority
- type: pserv
  name: mongo
  env: docker
  dockerfilePath: ./mongo/Dockerfile
  disks:
  - name: mongo-data
    mountPath: /data/db
    sizeGB: 10
- type: pserv
  name: caddy
  env: docker
  dockerfilePath: ./caddy/Dockerfile
  disks:
  - name: caddy-data
    mountPath: /data
    sizeGB: 10
  - name: caddy-config
    mountPath: /config
    sizeGB: 10