# Use a Node.js base image
FROM node:14 as build

# Set the working directory
WORKDIR /client-end

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Build the application
RUN npm run build

# Start a new stage from scratch
FROM node:14

WORKDIR /client-end

# Install serve
RUN npm install -g serve

# Copy the build output from the previous stage
COPY --from=build /client-end/build ./build

# Start the application
CMD ["serve", "-s", "build"]