# Use a Node 16 base image
FROM node:16-alpine

# Set the working directory to /back-end inside the container
WORKDIR /back-end

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port on which the app will be running
EXPOSE 3001

# Start the app
CMD ["npm","start"]